spring:
  application:
    name: teacher-event-processor

  kafka:
    client-id: "${spring.application.name}"
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    consumer:
      retry: 1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ms.teachers.management.consumer.teacher.kafka.contracts"
      group-id: teachers-consumer
    topics:
      teacher-info: ${TOPIC_TEACHER_INFO:teacher-info-topic}

server:
  port: 8081